/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

export const TUI_COPY_RESOURCES = {
  'mcp-status': {
    en: {
      title: 'MCP SERVERS',
      footer: {
        back: 'Esc back',
        readOnly: '↑/↓ scroll · q/Esc close',
        manage:
          'a Add · Enter Edit · Space Enable/disable · t Test · r Reconnect · d Remove · Esc Close',
        managePublication:
          'a Add · Enter Edit · Space Enable/disable · t Test · r Reconnect · d Remove · p Set provider credential · x Remove credential · Esc Close',
      },
      unavailableTitle: 'This TUI is not connected to a local MCP control plane.',
      unavailableDetail:
        'Client MCP tool association for remote Runtime Hosts is planned for a later release.',
      loading: 'Loading mcp.json and discovering tools…',
      loadError:
        'MCP configuration could not be loaded; no tools were published to the Runtime Host.',
      noServers: 'No MCP servers are configured. Press a to add one.',
      publication: {
        waiting: 'waiting to publish',
        host_unavailable: 'Runtime Host reconnecting',
        credential_required: 'provider credential required',
        credential_rejected: 'provider credential rejected',
        provider_conflict: 'provider active in another TUI',
        target_mismatch: 'provider target mismatch',
        publishing: 'publishing',
        published: 'published',
        not_published: 'not published',
        error: 'publication failed',
      },
      serverState: {
        disabled: 'disabled',
        disconnected: 'disconnected',
        connecting: 'connecting',
        connected: 'connected',
        'needs-auth': 'needs-auth',
        error: 'error',
      },
      configuredOnly: 'configured only',
      configPending: 'config pending',
      toolCount: '{count, plural, one {# tool} other {# tools}}',
      editor: {
        addTitle: 'Add MCP server',
        transportTitle: 'Transport',
        protocolTitle: 'Protocol preference',
        confirmAddTitle: 'Add this MCP server?',
        confirmImportTitle: 'Import MCP servers?',
        confirmRemoveTitle: 'Remove {serverId}?',
        confirmRemoveCredentialTitle: 'Remove the remote provider credential?',
        confirmRemoveCredentialDetail:
          'This stops publishing MCP tools to the selected Runtime Host.',
        confirmHint: 'y Confirm · Esc cancel',
        synchronizing: 'Configuration is synchronizing…',
        outOfSync: 'Durable configuration and MCP Manager are out of sync.',
        action: {
          test: 'Testing MCP server…',
          reconnect: 'Reconnecting MCP server…',
          apply: 'Applying MCP configuration…',
        },
        inputLabels: {
          server_id: 'Server ID',
          command: 'Command',
          args: 'Arguments',
          url: 'Streamable HTTP URL',
          cwd: 'Working directory',
          env: 'Environment',
          headers: 'Request headers',
          edit: 'Edit server JSON',
          import: 'Paste MCP JSON',
          publication_credential: 'Provider credential',
        },
        hints: {
          args: 'JSON string array, optional',
          map: 'JSON string map, optional',
          optional: 'optional',
          submit: 'Enter submit · Esc back',
          credential:
            'Stored only in the local credential store; never written to profiles, arguments, or chat · Enter submit · Esc back',
        },
        results: {
          exists: 'That server ID already exists.',
          stale_config: 'MCP configuration changed; retry the action.',
          stale_edit: 'This server changed; reopen it before editing.',
          stale_import: 'An imported entry changed; preview the import again.',
          missing: 'That server no longer exists.',
          closed: 'The MCP controller is closed.',
          'invalid-config': 'The server configuration is invalid.',
          'credential-cleanup-failed':
            'Stored credentials could not be removed; the configuration was not changed.',
          'publication-credential-failed':
            'The provider credential could not be stored or applied.',
          'persist-failed': 'The configuration could not be saved.',
          'manager-failed': 'The MCP connection action failed.',
          turn_active: 'MCP cannot be changed while a turn or another control action is running.',
          invalid: 'Check the value and try again.',
          published: 'Configuration saved and tools refreshed.',
          pending_host: 'Configuration saved; publication is waiting for Runtime Host.',
          sync_failed: 'Configuration saved, but the MCP manager is out of sync.',
          publication_failed: 'Configuration saved, but capability publication failed.',
          test_ok: 'Connection test passed.',
          test_failed: 'Connection test failed.',
          test_publication_failed: 'Connection test passed, but capability publication failed.',
          test_pending_host: 'Connection test passed; publication is waiting for Runtime Host.',
        },
      },
    },
    zh: {
      title: 'MCP 服务器',
      footer: {
        back: 'Esc 返回',
        readOnly: '↑/↓ 滚动 · q/Esc 关闭',
        manage: 'a 添加 · Enter 编辑 · Space 启用/停用 · t 测试 · r 重连 · d 删除 · Esc 关闭',
        managePublication:
          'a 添加 · Enter 编辑 · Space 启用/停用 · t 测试 · r 重连 · d 删除 · p 设置 Provider 凭据 · x 删除凭据 · Esc 关闭',
      },
      unavailableTitle: '当前 TUI 未连接本地 MCP 控制面。',
      unavailableDetail: '远程 Runtime Host 的客户端 MCP 工具关联将在后续版本提供。',
      loading: '正在读取 mcp.json 并发现工具…',
      loadError: '无法读取或应用 MCP 配置；没有向 Runtime Host 发布工具。',
      noServers: '尚未配置 MCP 服务器。按 a 添加。',
      publication: {
        waiting: '等待发布',
        host_unavailable: 'Runtime Host 重连中',
        credential_required: '需要 Provider 凭据',
        credential_rejected: 'Provider 凭据已被拒绝',
        provider_conflict: 'Provider 已在另一个 TUI 中运行',
        target_mismatch: 'Provider 目标不匹配',
        publishing: '正在发布',
        published: '已发布',
        not_published: '未发布',
        error: '发布失败',
      },
      serverState: {
        disabled: '已停用',
        disconnected: '未连接',
        connecting: '连接中',
        connected: '已连接',
        'needs-auth': '需要登录',
        error: '错误',
      },
      configuredOnly: '仅已配置',
      configPending: '配置待同步',
      toolCount: '{count} 个工具',
      editor: {
        addTitle: '添加 MCP 服务器',
        transportTitle: '传输方式',
        protocolTitle: '协议偏好',
        confirmAddTitle: '添加该 MCP 服务器？',
        confirmImportTitle: '导入 MCP 服务器？',
        confirmRemoveTitle: '删除 {serverId}？',
        confirmRemoveCredentialTitle: '删除远程 Provider 凭据？',
        confirmRemoveCredentialDetail: '这会停止向所选 Runtime Host 发布 MCP 工具。',
        confirmHint: 'y 确认 · Esc 取消',
        synchronizing: '配置同步中…',
        outOfSync: '持久化配置与 MCP Manager 尚未同步。',
        action: {
          test: '正在测试 MCP 服务器…',
          reconnect: '正在重连 MCP 服务器…',
          apply: '正在应用 MCP 配置…',
        },
        inputLabels: {
          server_id: '服务器 ID',
          command: '命令',
          args: '参数',
          url: 'Streamable HTTP URL',
          cwd: '工作目录',
          env: '环境变量',
          headers: '请求头',
          edit: '编辑服务器 JSON',
          import: '粘贴 MCP JSON',
          publication_credential: 'Provider 凭据',
        },
        hints: {
          args: 'JSON string array, 可留空',
          map: 'JSON string map, 可留空',
          optional: '可留空',
          submit: 'Enter 提交 · Esc 返回',
          credential: '仅保存到本机凭据存储；不会写入 profile、参数或对话 · Enter 提交 · Esc 返回',
        },
        results: {
          exists: '该服务器 ID 已存在。',
          stale_config: 'MCP 配置已变化，请重试。',
          stale_edit: '该服务器已变化，请重新打开后编辑。',
          stale_import: '导入项已变化，请重新预览。',
          missing: '该服务器已不存在。',
          closed: 'MCP 控制器已关闭。',
          'invalid-config': '服务器配置无效。',
          'credential-cleanup-failed': '无法删除旧凭据，配置未修改。',
          'publication-credential-failed': '无法保存或应用 Provider 凭据。',
          'persist-failed': '无法保存配置。',
          'manager-failed': 'MCP 连接操作失败。',
          turn_active: 'Turn 或其他控制操作运行期间不能修改 MCP。',
          invalid: '请检查输入后重试。',
          published: '配置已保存，工具已刷新。',
          pending_host: '配置已保存，正等待 Runtime Host 发布。',
          sync_failed: '配置已保存，但 MCP Manager 尚未同步。',
          publication_failed: '配置已保存，但 capability 发布失败。',
          test_ok: '连接测试通过。',
          test_failed: '连接测试失败。',
          test_publication_failed: '连接测试通过，但 capability 发布失败。',
          test_pending_host: '连接测试通过，正等待 Runtime Host 发布。',
        },
      },
    },
  },
  'form-interaction': {
    en: {
      requestedBy: 'Requested by {detail}',
      sensitiveWarning: 'Do not enter passwords, API keys, access tokens, or payment details.',
      required: 'required',
      optional: 'optional',
      omitted: 'omitted',
      empty: 'empty',
      invalid: "Value does not meet this field's constraints",
      reviewHint: '↑↓ field · Enter edit · Space include/omit · s submit · d decline · Esc cancel',
      textHint: 'Type a value · Enter review · Esc review',
      choiceHint: '↑↓ select · Enter review · Esc review',
      multiHint: '↑↓ move · Space toggle · Enter review · Esc review',
      trueValue: 'true',
      falseValue: 'false',
      selectedCount: '{count} selected',
    },
    zh: {
      requestedBy: '由 {detail} 请求',
      sensitiveWarning: '请勿输入密码、API 密钥、访问令牌或支付信息。',
      required: '必填',
      optional: '选填',
      omitted: '未提供',
      empty: '空',
      invalid: '该值不符合字段约束',
      reviewHint: '↑↓ 选择字段 · Enter 编辑 · Space 提供/省略 · s 提交 · d 拒绝 · Esc 取消',
      textHint: '输入值 · Enter 返回检查 · Esc 返回检查',
      choiceHint: '↑↓ 选择 · Enter 返回检查 · Esc 返回检查',
      multiHint: '↑↓ 移动 · Space 切换 · Enter 返回检查 · Esc 返回检查',
      trueValue: '是',
      falseValue: '否',
      selectedCount: '已选择 {count} 项',
    },
  },
  pickers: {
    en: {
      modelPickerTitle: 'Select Model',
      modelSwitchCacheWarning:
        '⚠ Switching models may rebuild the prompt cache; the next request may be slower or cost more.',
      modelSearchHint:
        'Search models / providers / connections · ↑↓ select · Enter confirm · Esc cancel',
      searchLabel: 'Search',
      noMatchingModels: 'No matching models',
      selectPickerHint: '↑↓ select · Enter confirm · Esc close',
      providerConfigured: 'configured',
      addAccount: 'add account',
      thinkingLevels: {
        off: 'Off',
        minimal: 'Minimal',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
        xhigh: 'Extra high',
        max: 'Maximum',
      },
      defaultThinkingLevel: 'Default',
      thinkingPickerTitle: 'Select Thinking Level',
      currentMarker: 'current',
      defaultMarker: 'default',
      setupTitle: 'Set Up Provider',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      onboardingUnavailable:
        'Onboarding is unavailable: this environment does not provide a setup surface.',
      onboardingRequestFailed: 'Could not reach the Runtime Host. Try again.',
      onboardingRejections: {
        provider_unsupported: 'This provider does not support API-key onboarding.',
        connection_not_found: 'This connection no longer exists. Reopen /setup and try again.',
        credential_not_configured: 'An API key is required.',
        base_url_not_configured: 'A Base URL is required for this provider.',
        catalog_full: 'The connection catalog is full.',
        model_unavailable: 'A selected model is no longer available. Verify and select again.',
        superseded: 'This connection changed. Reopen /setup and try again.',
      },
      onboardingFailures: {
        auth: 'Provider authentication failed. Check the API key and try again.',
        timeout: 'Provider verification timed out. Try again.',
        provider_unavailable: 'The provider is unavailable. Try again later.',
        network: 'A network error interrupted provider verification. Try again.',
        invalid_response: 'The provider returned an invalid response. Try again.',
        unknown: 'Provider verification failed. Try again.',
      },
      accountSavedRefreshFailed:
        'Account saved, but the model list has not refreshed. Restart Maka to reload it.',
      listProvidersFailed: 'Could not read configured connections.',
      noConfigurableProviders: 'No configurable API key providers are available.',
      baseUrlRequired: 'Enter a Base URL',
      baseUrlInvalid: 'Base URL is not a valid URL',
      baseUrlProtocol: 'Base URL must use http or https',
      baseUrlCredentials: 'Base URL cannot include credentials',
      baseUrlQuery: 'Base URL cannot include a query or fragment',
      baseUrlTooLong: 'Base URL cannot exceed 2048 bytes',
      selectModelBeforeSaving: 'Select at least one model before saving',
      reuseBaseUrlHint:
        'Leave blank to reuse the saved Base URL, or enter a replacement · Esc returns to provider selection',
      enterBaseUrlHint: 'Enter the relay Base URL (http/https) · Esc returns to provider selection',
      continueAction: 'Enter to continue',
      providerSearchHint: 'Search providers · ↑↓ select · Enter confirm · Esc cancel',
      noMatchingProviders: 'No matching providers',
      keyHints: {
        reuse: {
          baseUrl:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to Base URL',
          provider:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to provider selection',
        },
        enter: {
          baseUrl: 'Enter an API key · stored only on this machine · Esc returns to Base URL',
          provider:
            'Enter an API key · stored only on this machine · Esc returns to provider selection',
        },
      },
      submitAction: 'Enter to submit',
      verifyingKey: 'Verifying key…',
      modelSelectionHint: 'Search models · ↑↓ select · Space toggle · Enter save · Esc back',
      selectedModels: '{count} selected',
      selectedModelsAndSave: '{count} selected · Enter to save',
      saving: 'Saving…',
      complete: 'Complete',
      enabledModels: 'Models enabled: {count}',
      closeAction: 'Enter to close',
      thinkingUnsupported: 'This model does not support changing the thinking level.',
    },
    zh: {
      modelPickerTitle: '选择模型',
      modelSwitchCacheWarning: '⚠ 切换模型可能需要重建提示缓存；下一次请求可能更慢或成本更高。',
      modelSearchHint: '搜索模型 / 服务商 / 连接 · ↑↓ 选择 · Enter 确认 · Esc 取消',
      searchLabel: '搜索',
      noMatchingModels: '没有匹配的模型',
      selectPickerHint: '↑↓ 选择 · Enter 确认 · Esc 关闭',
      providerConfigured: '已设置',
      addAccount: '添加账号',
      thinkingLevels: {
        off: '关',
        minimal: '最小',
        low: '低',
        medium: '中',
        high: '高',
        xhigh: '超高',
        max: '最高',
      },
      defaultThinkingLevel: '默认',
      thinkingPickerTitle: '选择思考级别',
      currentMarker: '当前',
      defaultMarker: '默认',
      setupTitle: '配置模型提供商',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      onboardingUnavailable: 'Onboarding 不可用：当前运行环境未提供配置入口。',
      onboardingRequestFailed: '无法连接 Runtime Host，请重试。',
      onboardingRejections: {
        provider_unsupported: '该服务商不支持 API key 配置。',
        connection_not_found: '该连接已不存在，请重新打开 /setup 后重试。',
        credential_not_configured: '需要填写 API key。',
        base_url_not_configured: '该服务商需要填写 Base URL。',
        catalog_full: '连接目录已满。',
        model_unavailable: '所选模型已不可用，请重新验证并选择。',
        superseded: '该连接已发生变化，请重新打开 /setup 后重试。',
      },
      onboardingFailures: {
        auth: '服务商身份验证失败，请检查 API key 后重试。',
        timeout: '服务商验证超时，请重试。',
        provider_unavailable: '服务商当前不可用，请稍后重试。',
        network: '网络错误中断了服务商验证，请重试。',
        invalid_response: '服务商返回了无效响应，请重试。',
        unknown: '服务商验证失败，请重试。',
      },
      accountSavedRefreshFailed: '账号已保存，但模型列表暂未刷新。重启 Maka 后会重新载入。',
      listProvidersFailed: '无法读取已配置的连接。',
      noConfigurableProviders: '没有可配置的 API key 类供应商。',
      baseUrlRequired: '需要填写 Base URL',
      baseUrlInvalid: 'Base URL 不是有效的 URL',
      baseUrlProtocol: 'Base URL 必须使用 http 或 https',
      baseUrlCredentials: 'Base URL 不能包含账号密码',
      baseUrlQuery: 'Base URL 不能包含查询串或片段',
      baseUrlTooLong: 'Base URL 不能超过 2048 字节',
      selectModelBeforeSaving: '至少选择一个模型再保存',
      reuseBaseUrlHint: '留空复用已保存的 Base URL，或输入新地址替换 · Esc 返回选择服务商',
      enterBaseUrlHint: '输入中转站的 Base URL（http/https）· Esc 返回选择服务商',
      continueAction: 'Enter 继续',
      providerSearchHint: '搜索服务商，↑↓ 选择 · Enter 确认 · Esc 取消',
      noMatchingProviders: '没有匹配的服务商',
      keyHints: {
        reuse: {
          baseUrl: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回 Base URL',
          provider: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回选择服务商',
        },
        enter: {
          baseUrl: '输入 API key · 仅本机存储 · Esc 返回 Base URL',
          provider: '输入 API key · 仅本机存储 · Esc 返回选择服务商',
        },
      },
      submitAction: 'Enter 提交',
      verifyingKey: '正在验证 key…',
      modelSelectionHint: '搜索模型，↑↓ 选择 · Space 切换 · Enter 保存 · Esc 返回',
      selectedModels: '已选 {count}',
      selectedModelsAndSave: '已选 {count} · Enter 保存',
      saving: '正在保存…',
      complete: '完成',
      enabledModels: '已启用模型：{count}',
      closeAction: 'Enter 关闭',
      thinkingUnsupported: '当前模型不支持思考级别切换。',
    },
  },
  'primary-guidance': {
    en: {
      welcome: {
        tagline: 'Get things done together',
        start: 'Type a message to start',
        session: 'Switch or resume a session',
        model: 'Switch models',
        setup: 'Set up a model provider',
      },
      commands: {
        compact: 'Compact session context',
        context: 'Show latest request context usage',
        exit: 'Exit Maka',
        goal: 'Show autonomous goal status',
        graph: 'Show, enable, disable, or run one Graph turn',
        help: 'Show commands and keybindings',
        mcp: 'Manage client-owned MCP servers and tool publication status',
        model: 'Select model',
        move: 'Move current session to another directory',
        new: 'Start a new session',
        permissions: 'Set session permissions',
        recap: 'One-sentence recap of the session so far',
        rename: 'Rename current session',
        resume: 'Resume latest interrupted run at a safe boundary',
        rewind: 'Rewind to an earlier turn',
        session: 'Resume session',
        setup: 'Set up a model provider (API key)',
        side: 'Open a temporary side conversation',
        skill: 'Invoke a skill (or type /skill:<name> inline)',
        swarm: 'Show, enable, disable, or run one Swarm turn',
        thinking: 'Set thinking level',
        transcript: 'Browse the full transcript inside Maka',
      },
      help: {
        commandsHeading: 'Commands',
        userCommand: '  !<command> — run one shell command visible only to you',
        keybindingsHeading: 'Keybindings',
        keybindings: [
          '  Ctrl+O — expand or collapse all tool output',
          '  Ctrl+T — expand or collapse all thinking in view',
          '  Scroll the transcript with your terminal or trackpad',
          '  Enter (during a turn) — steer: inject a message into the running turn',
          '  Alt+Enter (during a turn) — queue a message for the next turn',
          '  Alt+↑ — take queued messages back into the editor to re-edit',
          '  Esc Esc (during a turn) — interrupt the turn',
          '  Esc Esc (when idle) — rewind to an earlier turn',
          '  Ctrl+C — stop the turn, clear input, or press twice to exit',
          '  Ctrl+D — exit when input is empty',
        ],
      },
    },
    zh: {
      welcome: {
        tagline: '陪你把事做完',
        start: '输入消息开始对话',
        session: '切换或恢复会话',
        model: '切换模型',
        setup: '配置模型提供商',
      },
      commands: {
        compact: '压缩会话上下文',
        context: '查看最近一次请求的上下文用量',
        exit: '退出 Maka',
        goal: '查看自主目标状态',
        graph: '查看、启用、停用 Graph 模式，或执行一次 Graph 任务',
        help: '查看命令和快捷键',
        mcp: '管理客户端 MCP 服务器和工具发布状态',
        model: '选择模型',
        move: '将当前会话移到其他目录',
        new: '新建会话',
        permissions: '设置会话权限',
        recap: '用一句话总结当前会话',
        rename: '重命名当前会话',
        resume: '从安全边界恢复最近一次中断的执行',
        rewind: '回退到较早的对话轮次',
        session: '切换或恢复会话',
        setup: '配置模型提供商（API Key）',
        side: '打开临时 Side Conversation',
        skill: '调用 Skill（也可直接输入 /skill:<name>）',
        swarm: '查看、启用、停用 Swarm 模式，或执行一次 Swarm 任务',
        thinking: '设置思考级别',
        transcript: '在 Maka 内浏览完整对话记录',
      },
      help: {
        commandsHeading: '命令',
        userCommand: '  !<command> — 执行一次仅用户可见的 shell 命令',
        keybindingsHeading: '快捷键',
        keybindings: [
          '  Ctrl+O — 展开或折叠所有工具输出',
          '  Ctrl+T — 展开或折叠视图中的所有思考块',
          '  使用终端或触控板滚动对话记录',
          '  Enter（任务运行中）— 将消息注入当前任务',
          '  Alt+Enter（任务运行中）— 将消息排入下一轮',
          '  Alt+↑ — 将已排队消息取回编辑器重新编辑',
          '  Esc Esc（任务运行中）— 中断当前任务',
          '  Esc Esc（空闲时）— 回退到较早的轮次',
          '  Ctrl+C — 停止任务、清空输入，或连续按两次退出',
          '  Ctrl+D — 输入为空时退出',
        ],
      },
    },
  },
  rewind: {
    en: {
      pickerTitle: 'Rewind',
      pending: 'Rewinding to before this turn…',
      doneRefilled:
        'Rewound to before this turn (branched into a new task; the original task is kept). The turn’s prompt was refilled into the input box — edit it and send again.',
      doneKeptDraft:
        'Rewound to before this turn (branched into a new task; the original task is kept). The input box already had unsent content and was left untouched; the turn’s prompt was saved to input history — press ↑ to recall it.',
      noTargets: 'No turns to rewind to.',
      busy: 'Cannot rewind: another action is in progress — wait for it to finish, or interrupt (Esc) and retry.',
      pickerHint:
        'Return to before the selected turn (discards it and later turns; the prompt refills the input box) · enter select / esc cancel',
    },
    zh: {
      pickerTitle: '回退',
      pending: '正在回退到该轮之前…',
      doneRefilled:
        '已回退到该轮之前（分支为新任务，原任务保留），该轮 prompt 已回填输入框，可修改后重新发送。',
      doneKeptDraft:
        '已回退到该轮之前（分支为新任务，原任务保留）。输入框已有未发送内容，未覆盖；该轮 prompt 已存入输入历史，可按 ↑ 找回。',
      noTargets: '没有可回退的轮次。',
      busy: '无法回退：当前有正在进行的操作 — 请等待其完成，或中断（Esc）后重试。',
      pickerHint: '回到选定轮次之前（丢弃该轮及之后，prompt 回填输入框） · enter 选择 / esc 取消',
    },
  },
  skills: {
    en: {
      pickerTitle: 'Invoke Skill',
      usage: 'Usage: /skill, or type /skill:<name> inline in a message',
      noneAvailable: 'No skills are available to invoke right now.',
      loaded: 'Skills loaded: {names}',
      loadFailed: 'Could not load skills {failures}; {outcome}',
      outcomeNoRequest: 'no model request was made.',
      outcomeMarkersNotSent: 'the failed invocation markers were not sent to the model.',
      failedItem: '/skill:{request} ({reason})',
      tooManyRequestsItem: 'more than the {limit}-request limit ({reason})',
      listSeparator: ', ',
      failureReasons: {
        invalid_name: 'invalid name',
        not_found: 'not found',
        disabled: 'disabled',
        host_incompatible: 'the current host is missing a tool it depends on',
        resolution_failed: 'resolution failed',
        too_many_requests: 'too many requests',
      },
    },
    zh: {
      pickerTitle: '调用技能',
      usage: 'Usage: /skill，或直接在消息中输入 /skill:<name>',
      noneAvailable: '当前没有可调用的技能。',
      loaded: '已加载技能：{names}',
      loadFailed: '未能加载技能 {failures}；{outcome}',
      outcomeNoRequest: '未发起模型请求。',
      outcomeMarkersNotSent: '失败的调用标记未发送给模型。',
      failedItem: '/skill:{request}（{reason}）',
      tooManyRequestsItem: '请求超过 {limit} 个上限（{reason}）',
      listSeparator: '、',
      failureReasons: {
        invalid_name: '名称无效',
        not_found: '未找到',
        disabled: '已禁用',
        host_incompatible: '当前主机缺少其依赖的工具',
        resolution_failed: '解析失败',
        too_many_requests: '调用请求过多',
      },
    },
  },
  'connection-identity': {
    en: {
      withRecovery: '{notice} {recovery}',
      emptyChoiceRecovery:
        'If /model has no choices, add or enable a connection first (run /setup for API-key connections).',
      confirmAccount:
        'This task comes from an older version and needs a one-time account confirmation. Run /model and choose an existing account and model.',
      accountDeleted:
        'The original account was deleted. Run /model and choose a new account and model to continue.',
      identityMismatch:
        'The saved account identity no longer matches its connection. Run /model and choose an account and model again.',
      accountDisabled:
        'The original account is disabled. Enable it, or run /model and choose a new account and model.',
    },
    zh: {
      withRecovery: '{notice}{recovery}',
      emptyChoiceRecovery:
        '如果 /model 没有可选项，请先添加或启用连接（API Key 连接可运行 /setup）。',
      confirmAccount: '此任务来自旧版本，需要确认一次账号。运行 /model 选择现有账号和模型。',
      accountDeleted: '原账号已删除；运行 /model 选择新账号和模型后继续。',
      identityMismatch: '任务保存的账号身份与当前连接不一致；运行 /model 重新选择账号和模型。',
      accountDisabled: '原账号已停用；请启用该账号，或运行 /model 选择新账号和模型。',
    },
  },
  'session-actions': {
    en: {
      foreignScanFailed: 'Could not read external conversations: {detail}',
      newSessionFailed: 'Could not start a new session. Try again shortly.',
    },
    zh: {
      foreignScanFailed: '读取外部对话失败：{detail}',
      newSessionFailed: '无法开始新会话，请稍后重试。',
    },
  },
  'pending-queue': {
    en: {
      steeringLabel: 'Steering:',
      queuedLabel: 'Queued:',
      requeueHint: 'Alt+↑ take queued messages back to re-edit',
    },
    zh: {
      steeringLabel: '注入：',
      queuedLabel: '已排队：',
      requeueHint: 'Alt+↑ 取回队列以重新编辑',
    },
  },
  'session-status': {
    en: {
      running: 'running',
      waitingForUser: 'waiting for you',
      permissionRequired: 'needs permission',
      connectionRequired: 'needs connection',
      signInRequired: 'needs sign-in',
      stopped: 'stopped',
    },
    zh: {
      running: '进行中',
      waitingForUser: '等你确认',
      permissionRequired: '需要权限',
      connectionRequired: '需要连接',
      signInRequired: '需要重新登录',
      stopped: '已中止',
    },
  },
} as const;
